### ISSUE TITLE
How to pass data from another in-memory variable

### ISSUE THREAD

**Issue by freddycct** [hpe-cct/cct-tutorial#3]
Hi, 

I am trying to learn how to use this tool. Let's suppose I have a matrix where each column is a data point that I am trying to feed into the `FullyConnectedLayer`

My matrix is a Breeze.linalg.DenseMatrix 

How do I pass it as a `DifferentiableField` to `FullyConnectedLayer` without storing the data in a file and using `ByteDataSource`?

**Comment by juliesymons** [comment]
Sensors are used to source external data into a compute graph in cct. `ByteDataSource` is a specific implementation of a `Sensor` used to read binary data from a file. You can create your own sensors using the cct API. Then as you step through the graph, new input data is read from the Sensor and fed into the graph. 

I wrote a simple example of a sensor that can be used for input to a `FullyConnectedLayer`, such as in the LogisticRegression example in cct-tutorial. This sensor generates random data, but I hope that you can leverage it to feed in your own data.

In LogisticRegression.scala, I replaced the line that calls `ByteDataSource` with:
`val data = DifferentiableField(new VectorSensor(Shape(5,1), Shape(tensorPoints),       
nextValue _, resetHook _), batchSize)`

Then I defined 2 two methods:`nextValue` and `resetHook`. nextValue gets invoked with each step of the compute graph. The reset method is optional if you want to be able to reset to a user-specified initial state when the compute graph is reset.  This code was added before the above line.

```
  Random.setDeterministic()
  val rng = new Random()
  var resetSeen = false

  val tensorShape = Shape(1)
  val tensorPoints = tensorShape.points * batchSize

  def resetHook() = {
    resetSeen = true
  }

  def nextValue() = Some(new Iterator[Vector] {
    if (resetSeen) {
      rng.nextFloatResetFirstIf(resetSeen)
      resetSeen = false
    }
    def next() = {
      val retVal = Vector(tensorPoints, (i) => rng.nextFloatResetFirstIf(resetSeen))
      retVal
    }
    def hasNext = true
  })

```

And I added the following: `import toolkit.neuralnetwork.DifferentiableField`
