### ISSUE TITLE
Is there a scaladoc for the CCT API?

### ISSUE THREAD

**Issue by mneary1** [hpe-cct/cct-tutorial#5]
It would be easier to reference rather than reading the source. I'm a scala novice, so does sbt allow you generate a scaladoc from the source?

**Comment by bchandle** [comment]
We're building it as a part of the release process, but weren't publishing it in a convenient location. You should see a set of -javadoc jars for the CCT API sitting in your Ivy cache.

To make the Scaladoc more usable, I've published the current API documentation to our Github Pages site and linked each module from the tutorial readme:

https://github.com/hpe-cct/cct-tutorial
